<?php
/**
 * Created by PhpStorm.
 * User: tsingsun
 * Date: 2017/2/24
 * Time: 下午4:28
 */

namespace tsingsun\swoole\di;

use Yii;

/**
 * 使用该类，替换了部分类的实现，方便YII项目的迁移
 * @package tsingsun\swoole\di
 */
class Container extends \yii\di\Container
{

    private $classCompatible = [
        'yii\web\Response' => 'tsingsun\swoole\web\Response',
        'yii\web\ErrorHandler' => 'tsingsun\swoole\web\ErrorHandler',
        'yii\log\Logger' => 'tsingsun\swoole\log\Logger',
        'yii\web\Session' => 'tsingsun\swoole\web\Session',
        'yii\log\FileTarget' => 'tsingsun\swoole\log\FileTarget',
        'yii\db\Command'       => 'tsingsun\swoole\db\Command',
        'yii\db\Connection'    => 'tsingsun\swoole\db\Connection',
        'yii\redis\Connection'    => 'tsingsun\swoole\redis\Connection',
        'yii\redis\Session'    => 'tsingsun\swoole\redis\Session',
    ];

    protected $autoReplace = true;

    public function setAutoReload($value)
    {
        $this->autoReplace = $value;
    }

    public function get($class, $params = [], $config = [])
    {
        return parent::get($class, $params, $config); // TODO: Change the autogenerated stub
    }


    protected function build($class, $params, $config)
    {
        if ($this->autoReplace && isset($this->classCompatible[$class])) {
            $class = $this->classCompatible[$class];
        }
        return parent::build($class, $params, $config); // TODO: Change the autogenerated stub
    }


}