<?php
/**
 * Created by PhpStorm.
 * User: tsingsun
 * Date: 2017/2/22
 * Time: 下午6:01
 */

namespace swooleunit\controllers;


use swooleunit\TestCase;
use yii\httpclient\Client;
use yii\swoole\helper\AsyncHelper;
use yii\swoole\Controllers\SwooleController;
use yii\swoole\promise\Promise;


class AsyncHelperTest extends TestCase
{
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->mockApplication();
    }


    function testParseUrl(){
        $url = 'https://www.baidu.com/apc?abc';
        $val = AsyncHelper::parseRemoteInfo($url);
        $this->assertEquals('https',$val['scheme']);
        $this->assertEquals('www.baidu.com',$val['host']);
        $this->assertEquals('/apc',$val['path']);
        $this->assertEquals('abc',$val['query']);
    }

    function testDnsLooup(){
        $url = 'www.baidu.com';
        $result = AsyncHelper::dnsLookup($url);
//        $result->wait();
        print_r($result);
    }

    public function testInvokesWaitFunction()
    {
//        swoole_async_dns_lookup($host, function($host, $ip) use (&$promise) {
//            if ($ip) {
//                $promise->resolve($ip);
//            }
//            else {
//                $promise->reject(new \Exception("Can't reslove host: $host"));
//            }
//        });

        $p = new Promise(function () use (&$p) {
            $url = 'www.baidu.com';
            $p->resolve(yield AsyncHelper::dnsLookup($url)); }
        );
        $this->assertEquals('10', $p->wait());
    }


}
