<?php
/**
 * Created by PhpStorm.
 * User: tsingsun
 * Date: 2017/2/22
 * Time: 下午6:01
 */

namespace swooleunit\controllers;


use swooleunit\TestCase;
use yii\swoole\promise\Promise;

class PromiseTest extends TestCase
{
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->mockApplication();
    }

    public function testInvokesWaitFunction()
    {
        $url = parse_url('http://www.baidu.com');
        $dns_lookup = Promise\promisify('swoole_async_dns_lookup',function($promise){$promise->resolve(1);});
        $ret = $dns_lookup($url['host']);
        print_r($ret);
        $val = $ret->wait();
//        $loop = \Yii::$app->get('eventloop')->loop;
//        $val = Promise\await($ret,$loop);
    }
}
